### ISSUE TITLE
GAMES101: 现代计算机图形学入门

### ISSUE THREAD

**Issue by hanyangl5** [biyuruofeng/Computer-science-live-open-course#1]
课程主页：https://sites.cs.ucsb.edu/~lingqi/teaching/games101.html
课程录像：https://www.bilibili.com/video/av90798049
闫令琪老师讲的现代计算机图形学入门，由浅入深，通俗易懂，算是国内数一数二的计算机图形学入门课
全面而系统地介绍现代计算机图形学的四大组成部分：（1）光栅化成像，（2）几何表示，（3）光的传播理论，（4）动画与模拟

**Comment by Chenliang-Gu** [comment]
你好，谢谢提交，已经放进去啦
